---
title: "map_corals"
author: "ross"
date: "12/4/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(parzer)
library(tidyverse)
library(lubridate)
```

```{r}
# Read in coral collection info
md <- read_csv("data/datasheets/Collection_data.csv") %>%
  unite("date_time", date, time, `AM/PM`, sep = " ", remove = TRUE) %>%
  mutate(date_time = ymd_hms(date_time, tz = "Pacific/Pago_Pago"),
         date_time_min = format(date_time, "%F %H:%M"))

# md <- md %>%
#   separate(position, into = c("lat", "lon"), sep = "' ") %>%
#   mutate(lat = parse_lat(lat), lon = parse_lon(lon))
# 
# write_csv(md, "colony_metadata_parsed.csv")

# md[which(duplicated(md$basket)),]

```

```{r}
# Read in GPS tracks
gps_track_files <- list.files("data/GPS", pattern = ".csv", full.names = TRUE)

# Dynamically read files that have single or multiple tracks (variable numbers of lines before header row)
# Define a function to read each CSV with a flexible header row
read_csv_with_flexible_header <- function(file_path) {
  # Read in the first few lines to determine header location
  lines <- readr::read_lines(file_path, n_max = 100)  # Adjust n_max if header may be farther down
  
  # Find the line that contains the expected column name pattern
  header_row <- which(grepl("trksegID", lines))[1]  # replace with actual column name pattern
  
  # Read the CSV starting from the header row
  readr::read_csv(file_path, skip = header_row - 1)
}

gps_tracks0 <- map_dfr(gps_track_files, read_csv_with_flexible_header, .id = "file_id")

# Tidy
gps_tracks1 <- gps_tracks0 %>%
  janitor::clean_names() %>%
  mutate(file_id = basename(gps_track_files[as.numeric(file_id)]),
         gps_id = str_sub(file_id, start = 1, end = 4))


# Convert to correct time zone, and get date sampled (conversion needs to be done before getting date because dateline)
gps_tracks2 <- gps_tracks1 %>%
  select(gps_id, time, lat, lon) %>%
  mutate(date_time = as_datetime(time, tz = "Pacific/Pago_Pago"),
         date = as_date(date_time),
         date_time_min = format(date_time, "%F %H:%M"))


# Get last lat/lon recorded for each discrete minute
gps_tracks3 <- gps_tracks2 %>%
  group_by(gps_id, date_time_min) %>%
  summarise(across(everything(), last))

gps_tracks3
```

```{r}
# Pull coral lat/lon from gps tracks based on date/time sampled
df <- left_join(md, gps_tracks3, by = c("gps_id", "date_time_min"))

View(df)
```

```{r}
# Plot whole tracks?
ggplot(gps_tracks3, aes(x = lon, y = lat)) +
  geom_point() +
  theme_minimal()
```

```{r}
library(sf)
library(osmdata)

# Tutuila outline from OpenStreetMap (reasonably high-res)
tutuila <- opq(bbox = c(-170.85, -14.43, -170.50, -14.18)) %>%
  add_osm_feature(key = "place", value = "island") %>%
  add_osm_feature(key = "name", value = "Tutuila") %>%
  osmdata_sf() %>%
  pluck("osm_multipolygons") %>%
  st_make_valid()

ggtut <- ggplot(tutuila) +
  geom_sf(fill = NA, color = "black", linewidth = 0.5) +
  coord_sf(expand = FALSE) +
  theme_void()

dfsumm <- df %>%
  group_by(location) %>%
  summarize(n = n(),
            lat = mean(lat, na.rm = T),
            lon = mean(lon, na.rm = T))

ggtut +
  geom_point(data = dfsumm, aes(x = lon, y = lat, size = n), color = "red", pch = 16, alpha = 0.8)

```





